version: 0.0
os: linux
files:
  - source: target/app.jar
    destination: /home/ubuntu/spring-app/
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root